# Generated by Django 5.0.6 on 2024-06-28 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hpced', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='search_access_token',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='search_expires_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='search_resource_server',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='search_scope',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
